//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystemClient.CourseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/EnrollmentSystemService")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseServiceReference.ICourseService")]
    public interface ICourseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/getCourses", ReplyAction="http://tempuri.org/ICourseService/getCoursesResponse")]
        EnrollmentSystemClient.CourseServiceReference.Course[] getCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/getCourses", ReplyAction="http://tempuri.org/ICourseService/getCoursesResponse")]
        System.Threading.Tasks.Task<EnrollmentSystemClient.CourseServiceReference.Course[]> getCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/addCourse", ReplyAction="http://tempuri.org/ICourseService/addCourseResponse")]
        void addCourse(int courseId, string courseName, decimal cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/addCourse", ReplyAction="http://tempuri.org/ICourseService/addCourseResponse")]
        System.Threading.Tasks.Task addCourseAsync(int courseId, string courseName, decimal cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/getACourse", ReplyAction="http://tempuri.org/ICourseService/getACourseResponse")]
        EnrollmentSystemClient.CourseServiceReference.Course getACourse(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/getACourse", ReplyAction="http://tempuri.org/ICourseService/getACourseResponse")]
        System.Threading.Tasks.Task<EnrollmentSystemClient.CourseServiceReference.Course> getACourseAsync(int courseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServiceChannel : EnrollmentSystemClient.CourseServiceReference.ICourseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServiceClient : System.ServiceModel.ClientBase<EnrollmentSystemClient.CourseServiceReference.ICourseService>, EnrollmentSystemClient.CourseServiceReference.ICourseService {
        
        public CourseServiceClient() {
        }
        
        public CourseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EnrollmentSystemClient.CourseServiceReference.Course[] getCourses() {
            return base.Channel.getCourses();
        }
        
        public System.Threading.Tasks.Task<EnrollmentSystemClient.CourseServiceReference.Course[]> getCoursesAsync() {
            return base.Channel.getCoursesAsync();
        }
        
        public void addCourse(int courseId, string courseName, decimal cost) {
            base.Channel.addCourse(courseId, courseName, cost);
        }
        
        public System.Threading.Tasks.Task addCourseAsync(int courseId, string courseName, decimal cost) {
            return base.Channel.addCourseAsync(courseId, courseName, cost);
        }
        
        public EnrollmentSystemClient.CourseServiceReference.Course getACourse(int courseId) {
            return base.Channel.getACourse(courseId);
        }
        
        public System.Threading.Tasks.Task<EnrollmentSystemClient.CourseServiceReference.Course> getACourseAsync(int courseId) {
            return base.Channel.getACourseAsync(courseId);
        }
    }
}
